events {
    worker_connections 1024;
}

http {
    # This tells Nginx how to find the other containers in the Swarm network
    resolver 127.0.0.11 valid=10s;

    server {
        listen 80;

       location /health {
          return 200 'OK';
       }

        # Root goes to the Vote App
        location / {
            proxy_pass http://vote:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # /result goes to the Result App
        location /result {
            proxy_pass http://result:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}