services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    configs:
      - source: nginx_config_v21
        target: /etc/nginx/nginx.conf
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1
  vote:
    image: nikkytechies/voting-app-vote:latest
    environment:
      - REDIS_HOST=redis
    networks:
      - frontend
      - backend
    depends_on:
      - redis

  result:
    image: nikkytechies/voting-app-result:latest
    ports:
      - "5001:3000"  
    networks:
      - frontend     # To talk to Nginx
      - backend      # To talk to Redis
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
    deploy:
      replicas: 1
    

  db:
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend
    secrets:
      - db_password

  worker:
    image: nikkytechies/voting-worker:latest
    networks:
      - frontend
      - backend
    secrets:
      - db_password

  redis:
    image: redis:alpine
    networks:
      - backend
      

volumes:
  db-data:
  
networks:
  frontend:
  backend:

secrets:
  db_password:
    file: ./db_password.txt
    external: true

configs:
  nginx_config_v21:
    file: ./nginx.conf 