services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    configs:
      - source: nginx_config_v21
        target: /etc/nginx/nginx.conf
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

    # FEATURE: Production Hardening
    # read_only: true
    # tmpfs:
    #   - /var/cache/nginx:uid=101,gid=101
    #   - /var/run:uid=101,gid=101
    #   - /tmp:uid=101,gid=101

    # FEATURE: Self-Healing (Checks if Port 80 is responding)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

    dns:
      - 8.8.8.8
      - 8.8.4.4

# The Voting UI
  vote:
    image: nikkytechies/voting-app-vote:latest
    networks:
      - frontend
      - backend
    environment:
      - REDIS_URL=redis://redis:6379
    deploy:
      replicas: 3 # FEATURE: Docker Swarm Basics
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
      restart_policy:
        condition: on-failure

    logging:
      driver: "json-file"
      options:
       max-size: "10m" # Keep only 10MB of logs
       max-file: "3"   # Keep only the last 3 files

  worker:
    image: nikkytechies/voting-worker:latest
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1
    
# The WebSocket Result Gateway
  result:
    image: nikkytechies/voting-app-result:latest
    ports:
      - "5001:3000"
    networks:
      - frontend
      - backend
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - NODE_ENV=production
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 128M

    logging:
      driver: "json-file"
      options:
       max-size: "10m" # Keep only 10MB of logs
       max-file: "3"   # Keep only the last 3 files

   # Redis with Persistence
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"] # Advanced: Save data to disk
    networks:
      - backend
  cadvisor:
    image: gcr.io/cadvisor/cadvisor-amd64:v0.47.2
    privileged: true
    user: root
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw # Changed to Read/Write
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - backend
   
  db:
    volumes:
      - prod-db-data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == manager] # Keep DB on manager node

  # FEATURE: Visualization (Grafana)
  grafana:
    image: grafana/grafana:latest
    user: "472" # Standard Grafana User ID
    ports:
      - "4000:3000"
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure

    dns:
      - 8.8.8.8
      - 8.8.4.4

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    networks:
      - backend
    configs:
      - source: prom_config
        target: /etc/prometheus/prometheus.yml
    deploy:
      placement:
        constraints: [node.role == manager]

    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  prod-db-data:

networks:
  frontend:
  backend:

configs:
  nginx_config_v21:
    file: ./nginx.conf
  prom_config:
    file: ./prometheus.yml
