name: CI/CD Final Project 

on:
  push:
    branches: [ "main" ]

    paths:
      - '04-containerization/projects/microservices/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**/microservices/**'
  #Added: Allows you to trigger the build manually from the GitHub Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./04-containerization/projects/microservices/voting-app-project
    strategy:
      matrix:
        service: [vote, result, worker]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Path Debugger
        run: |
          echo "Current Directory: $(pwd)"
          echo "Listing all files:"
          find . -maxdepth 3 -not -path '*/.*'
          
      - name: Build Local Image for Testing
        run: |
          docker build -t test-image:${{ github.sha }} ./${{ matrix.service }}
      # FEATURE: Trivy Security Scan
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'test-image:${{ github.sha }}'
          format: 'table'
          exit-code: '1' # This stops the pipeline if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Login to Docker Hub
        if: success() # Only login if the security scan passes
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        if: success()
        uses: docker/build-push-action@v5
        with:
          # Use the GITHUB_WORKSPACE variable to ensure we always start from the root
          context: ${{ github.workspace }}/04-containerization/projects/microservices/voting-app-project/${{ matrix.service }}
          # The Action will automatically find the Dockerfile inside the context
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/voting-${{ matrix.service }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/voting-${{ matrix.service }}:${{ github.sha }}